services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      - "PGADMIN_DEFAULT_EMAIL=admin@example.com"
      - "PGADMIN_DEFAULT_PASSWORD=admin"
    ports:
      - "4100:80"
    volumes:
      - "${STORAGE_DIR}/:/var/lib/pgadmin"
    networks:
      postgresql:
        ipv4_address: [REDACTED_IP]
    restart: unless-stopped

networks:
  postgresql:
    name: postgresql
    driver: bridge
    ipam:
      config:
        - subnet: [REDACTED_IP]/24
